# encoding: utf-8

# Comunas de Chile
# See http://www.subdere.gov.cl/documentacion/regiones-provincias-y-comunas-de-chile
# Last modified: 2013-02-12
#
# Note: the 'ciudad' is not an administrative division, yet is widely used by people.
#
Comuna.find_or_create_by_name!(name: "Camarones", code: "15102", provincia: "Arica", region: "Arica y Parinacota", region_number: "XV")
Comuna.find_or_create_by_name!(name: "Putre", code: "15201", provincia: "Parinacota", region: "Arica y Parinacota", region_number: "XV")
Comuna.find_or_create_by_name!(name: "General Lagos", code: "15202", provincia: "Parinacota", region: "Arica y Parinacota", region_number: "XV")
Comuna.find_or_create_by_name!(name: "Iquique", code: "01101", provincia: "Iquique", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Alto Hospicio", code: "01102", provincia: "Iquique", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Pozo Almonte", code: "01201", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Camiña", code: "01402", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Colchane", code: "01403", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Huara", code: "01404", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Pica", code: "01405", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Antofagasta", code: "02101", provincia: "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Mejillones", code: "02102", provincia: "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Sierra Gorda", code: "02103", provincia:   "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Taltal", code: "02104", provincia: "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Calama", code: "02201", provincia: "El Loa", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Ollagüe", code: "02202", provincia: "El Loa", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "San Pedro de Atacama", code: "02203", provincia: "El Loa", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Tocopilla", code: "02301", provincia: "Tocopilla", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "María Elena", code: "02302", provincia: "Tocopilla", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Copiapó", code: "03101", provincia: "Copiapó", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Caldera", code: "03102", provincia: "Copiapó", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Tierra Amarilla", code: "03103", provincia: "Copiapó", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Chañaral", code: "03201", provincia: "Chañaral", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Diego de Almagro", code: "03202", provincia: "Chañaral", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Vallenar", code: "03301", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Alto del Carmen", code:"03302", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Freirina", code: "03303", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Huasco", code: "03304", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "La Serena", code: "04101", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Coquimbo", code: "04102", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Andacollo", code: "04103", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "La Higuera", code: "04104", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Paiguano", code: "04105", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Vicuña", code: "04106", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Illapel", code: "04201", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Canela", code: "04202", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Los Vilos", code: "04203", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Salamanca", code: "04204", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Ovalle", code: "04301", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Combarbalá", code: "04302", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Monte Patria", code: "04303", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Punitaqui", code: "04304", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Río Hurtado", code: "04305", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Valparaíso", code: "05101", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Casablanca", code: "05102", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Concón", code: "05103", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Juan Fernández", code: "05104", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Puchuncaví", code: "05105", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Quintero", code: "05107", provincia: "Valparaíso", region: "Valparaíso", region_number: "V") # 05107
Comuna.find_or_create_by_name!(name: "Viña del Mar", code: "05109", provincia: "Valparaíso", region: "Valparaíso", region_number: "V") # 05109
Comuna.find_or_create_by_name!(name: "Isla de Pascua", code: "05201", provincia: "Isla de Pascua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Los Andes", code: "05301", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Calle Larga", code: "05302", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Riconada", code: "05303", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "San Esteban", code: "05304", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "La Ligua", code: "05401", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Cabildo", code: "05402", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Papudo", code: "05403", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Petorca", code: "05404", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Zapallar", code: "05405", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Quillota", code: "05501", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Calera", code: "05502", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Hijuelas", code: "05503", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "La Cruz", code: "05504", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Nogales", code: "05506", provincia: "Quillota", region: "Valparaíso", region_number: "V") # 05506
Comuna.find_or_create_by_name!(name: "San Antonio", code: "05601", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Algarrobo", code: "05602", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Cartagena", code: "05603", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "El Quisco", code: "05604", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "El Tabo", code: "05605", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Santo Domingo", code: "05606", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "San Felipe", code: "05701", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Catemu", code: "05702", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Llaillay", code: "05703", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Panquehue", code: "05704", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Putaendo", code: "05705", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Santa María", code: "05706", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Quilpué", code: "05801", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Limache", code: "05802", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Olmué", code: "05803", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Villa Alemana", code: "05804", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name({name: "Rancagua", code: "06101", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Codegua", code: "06102", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Coinco", code: "06103", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Coltauco", code: "06104", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Doñihue", code: "06105", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Graneros", code: "06106", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Las Cabras", code: "06107", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Machalí", code: "06108", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Malloa", code: "06109", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Mostazal", code: "06110", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Olivar", code: "06111", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Peumo", code: "06112", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Pichidegua", code: "06113", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Quinta de Tilcoco", code: "06114", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Rengo", code: "06115", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Requínoa", code: "06116", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "San Vicente", code: "06117", provincia: "Cachapoal", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Pichilemu", code: "06201", provincia: "Cardenal Caro", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "La Estrella", code: "06202", provincia: "Cardenal Caro", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Litueche", code: "06203", provincia: "Cardenal Caro", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Marichihue", code: "06204", provincia: "Cardenal Caro", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Navidad", code: "06205", provincia: "Cardenal Caro", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Paredones", code: "06206", provincia: "Cardenal Caro", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "San Fernando", code: "06301", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Chépica", code: "06302", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Chimbarongo", code: "06303", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Lolol", code: "06304", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Nancagua", code: "06305", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Palmilla", code: "06306", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Peralillo", code: "06307", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Placilla", code: "06308", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Pumanque", code: "06309", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Santa Cruz", code: "06310", provincia: "Colchagua", region: "Región del Libertador Gral. Bernardo O'Higgins", region_number: "VI")
Comuna.find_or_create_by_name({name: "Talca", code: "07101", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Constitución", code: "07102", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Curepto", code: "07103", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Empedrado", code: "07104", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Maule", code: "07105", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Pelarco", code: "07106", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Pencahue", code: "07107", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Río Claro", code: "07108", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "San Clemente", code: "07109", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "San Rafael", code: "07110", provincia: "Talca", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Cauquenes", code: "07201", provincia: "Cauquenes", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Chanco", code: "07202", provincia: "Cauquenes", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Pelluhue", code: "07203", provincia: "Cauquenes", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Curicó", code: "07301", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Hualañé", code: "07302", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Licantén", code: "07303", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Molina", code: "07304", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Rauco", code: "07305", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Romeral", code: "07306", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Sagrada Familia", code: "07307", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Teno", code: "07308", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Vichuquén", code: "07309", provincia: "Curicó", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Linares", code: "07401", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Colbún", code: "07402", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Longaví", code: "07403", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Parral", code: "07404", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Retiro", code: "07405", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "San Javier", code: "07406", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Villa Alegre", code: "07407", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Yerbas Buenas", code: "07408", provincia: "Linares", region: "Región del Maule", region_number: "VII")
Comuna.find_or_create_by_name({name: "Concepción", code: "08101", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Coronel", code: "08102", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Chiguayante", code: "08103", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Florida", code: "08104", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Hualqui", code: "08105", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Lota", code: "08106", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Penco", code: "08107", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "San Pedro de la Paz", code: "08108", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Santa Juana", code: "08109", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Talcahuano", code: "08110", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Tomé", code: "08111", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Hualpén", code: "08112", provincia: "Concepción", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Lebu", code: "08201", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Arauco", code: "08202", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Cañete", code: "08203", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Contulmo", code: "08204", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Curanilahue", code: "08205", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Los Álamos", code: "08206", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Tirúa", code: "08207", provincia: "Arauco", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Los Ángeles", code: "08301", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Antuco", code: "08302", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Cabrero", code: "08303", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Laja", code: "08304", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Mulchén", code: "08305", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Nacimiento", code: "08306", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Negrete", code: "08307", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Quilaco", code: "08308", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Quilleco", code: "08309", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "San Rosendo", code: "08310", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Santa Bárbara", code: "08311", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Tucapel", code: "08312", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Yumbel", code: "08313", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Alto Biobío", code: "08314", provincia: "Biobío", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Chillán", code: "08401", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Bulnes", code: "08402", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Cobquecura", code: "08403", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Coelemu", code: "08404", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Coihueco", code: "08405", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Chillán Viejo", code: "08406", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "El Carmen", code: "08407", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Ninhue", code: "08408", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Ñiquén", code: "08409", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Pemuco", code: "08410", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Pinto", code: "08411", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Portezuelo", code: "08412", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Quillón", code: "08413", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Quirihue", code: "08414", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Ránquil", code: "08415", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "San Carlos", code: "08416", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "San Fabián", code: "08417", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "San Ignacio", code: "08418", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "San Nicolás", code: "08419", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Treguaco", code: "08420", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Yungay", code: "08421", provincia: "Ñuble", region: "Región del Biobío", region_number: "VIII")
Comuna.find_or_create_by_name({name: "Temuco", code: "09101", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Carahu", code: "09102", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Cunco", code: "09103", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Curarrehue", code: "09104", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Freire", code: "09105", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Galvarin", code: "09106", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Gorbea", code: "09107", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Lautar", code: "09108", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Loncoche", code: "09109", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Melipeuco", code: "09110", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Nueva Imperial", code: "09111", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Padre las Casa", code: "09112", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Perquenco", code: "09113", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Pitrufquén", code: "09114", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Pucó", code: "09115", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Saavedra", code: "09116", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Teodoro Schmid", code: "09117", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Toltén", code: "09118", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Vilcún", code: "09119", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Villarrica", code: "09120", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Cholchol", code: "09121", provincia: "Cautín", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Angol", code: "09201", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Collipulli", code: "09202", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Curacautín", code: "09203", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Ercilla", code: "09204", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Lonquimay", code: "09205", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Los Sauces", code: "09206", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Lumaco", code: "09207", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Purén", code: "09208", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Renaico", code: "09209", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Traiguén", code: "09210", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Victoria", code: "09211", provincia: "Malleco", region: "Región de la Araucanía", region_number: "IX")
Comuna.find_or_create_by_name({name: "Valdivia", code: "14101", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Corral", code: "14102", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Lanco", code: "14103", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Los Lagos", code: "14104", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Máfil", code: "14105", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Mariquina", code: "14106", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Paillaco", code: "14107", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "Panguipulli", code: "14108", provincia: "Valdivia", region: "Región de los Ríos", region_number: "XIV")
Comuna.find_or_create_by_name({name: "La Unión", code: "14201", provincia: "Ranco", region: "Región de los Ríos", region_number: "XIV"
Comuna.find_or_create_by_name({name: "Futrono", code: "14201", provincia: "Ranco", region: "Región de los Ríos", region_number: "XIV"
Comuna.find_or_create_by_name({name: "Lago Ranco", code: "14201", provincia: "Ranco", region: "Región de los Ríos", region_number: "XIV"
Comuna.find_or_create_by_name({name: "Río Bueno", code: "14201", provincia: "Ranco", region: "Región de los Ríos", region_number: "XIV"
Comuna.find_or_create_by_name({name: "Puerto Montt", code: "10101", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Calbuco", code: "10102", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Cochamó", code: "10103", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Fresia", code: "10104", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Frutillar", code: "10105", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Los Muermos", code: "10106", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Llanquihue", code: "10107", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Maullín", code: "10108", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Puerto Varas", code: "10109", provincia: "Llanquihue", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Castro", code: "10201", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Ancud", code: "10202", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Chonchi", code: "10203", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Curaco de Vélez", code: "10204", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Dalcahue", code: "10205", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Puqueldón", code: "10206", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Queilén", code: "10207", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Quellón", code: "10208", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Quemchi", code: "10209", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Quinchao", code: "10210", provincia: "Chiloé", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Osorno", code: "10301", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Puerto Octay", code: "10302", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Purranque", code: "10303", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Puyehue", code: "10304", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Río Negro", code: "10305", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "San Juan de la Costa", code: "10306", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "San Pablo", code: "10307", provincia: "Osorno", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Chaitén", code: "10401", provincia: "Palena", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Futaleufú", code: "10402", provincia: "Palena", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Hualaihué", code: "10403", provincia: "Palena", region: "Región de los Lagos", region_number: "X")
Comuna.find_or_create_by_name({name: "Palena", code: "10404", provincia: "Palena", region: "Región de los Lagos", region_number: "X")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")