# encoding: utf-8

# Comunas de Chile
# See http://www.subdere.gov.cl/documentacion/regiones-provincias-y-comunas-de-chile
# Last modified: 2012-12-26
#
# Note: the 'ciudad' is not an administrative division, yet is widely used by people.
#
Comuna.find_or_create_by_name!(name: "Camarones", code: "15102", provincia: "Arica", region: "Arica y Parinacota", region_number: "XV")
Comuna.find_or_create_by_name!(name: "Putre", code: "15201", provincia: "Parinacota", region: "Arica y Parinacota", region_number: "XV")
Comuna.find_or_create_by_name!(name: "General Lagos", code: "15202", provincia: "Parinacota", region: "Arica y Parinacota", region_number: "XV")
Comuna.find_or_create_by_name!(name: "Iquique", code: "01101", provincia: "Iquique", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Alto Hospicio", code: "01102", provincia: "Iquique", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Pozo Almonte", code: "01201", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Camiña", code: "01402", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Colchane", code: "01403", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Huara", code: "01404", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Pica", code: "01405", provincia: "Tamarugal", region: "Tarapacá", region_number: "I")
Comuna.find_or_create_by_name!(name: "Antofagasta", code: "02101", provincia: "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Mejillones", code: "02102", provincia: "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Sierra Gorda", code: "02103", provincia:   "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Taltal", code: "02104", provincia: "Antofagasta", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Calama", code: "02201", provincia: "El Loa", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Ollagüe", code: "02202", provincia: "El Loa", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "San Pedro de Atacama", code: "02203", provincia: "El Loa", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Tocopilla", code: "02301", provincia: "Tocopilla", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "María Elena", code: "02302", provincia: "Tocopilla", region: "Antofagasta", region_number: "II")
Comuna.find_or_create_by_name!(name: "Copiapó", code: "03101", provincia: "Copiapó", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Caldera", code: "03102", provincia: "Copiapó", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Tierra Amarilla", code: "03103", provincia: "Copiapó", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Chañaral", code: "03201", provincia: "Chañaral", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Diego de Almagro", code: "03202", provincia: "Chañaral", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Vallenar", code: "03301", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Alto del Carmen", code:"03302", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Freirina", code: "03303", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "Huasco", code: "03304", provincia: "Huasco", region: "Atacama", region_number: "III")
Comuna.find_or_create_by_name!(name: "La Serena", code: "04101", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Coquimbo", code: "04102", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Andacollo", code: "04103", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "La Higuera", code: "04104", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Paiguano", code: "04105", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Vicuña", code: "04106", provincia: "Elqui", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Illapel", code: "04201", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Canela", code: "04202", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Los Vilos", code: "04203", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Salamanca", code: "04204", provincia: "Choapa", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Ovalle", code: "04301", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Combarbalá", code: "04302", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Monte Patria", code: "04303", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Punitaqui", code: "04304", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Río Hurtado", code: "04305", provincia: "Limarí", region: "Coquimbo", region_number: "IV")
Comuna.find_or_create_by_name!(name: "Valparaíso", code: "05101", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Casablanca", code: "05102", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Concón", code: "05103", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Juan Fernández", code: "05104", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Puchuncaví", code: "05105", provincia: "Valparaíso", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Quintero", code: "05107", provincia: "Valparaíso", region: "Valparaíso", region_number: "V") # 05107
Comuna.find_or_create_by_name!(name: "Viña del Mar", code: "05109", provincia: "Valparaíso", region: "Valparaíso", region_number: "V") # 05109
Comuna.find_or_create_by_name!(name: "Isla de Pascua", code: "05201", provincia: "Isla de Pascua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Los Andes", code: "05301", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Calle Larga", code: "05302", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Riconada", code: "05303", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "San Esteban", code: "05304", provincia: "Los Andes", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "La Ligua", code: "05401", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Cabildo", code: "05402", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Papudo", code: "05403", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Petorca", code: "05404", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Zapallar", code: "05405", provincia: "Petorca", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Quillota", code: "05501", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Calera", code: "05502", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Hijuelas", code: "05503", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "La Cruz", code: "05504", provincia: "Quillota", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Nogales", code: "05506", provincia: "Quillota", region: "Valparaíso", region_number: "V") # 05506
Comuna.find_or_create_by_name!(name: "San Antonio", code: "05601", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Algarrobo", code: "05602", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Cartagena", code: "05603", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "El Quisco", code: "05604", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "El Tabo", code: "05605", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Santo Domingo", code: "05606", provincia: "San Antonio", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "San Felipe", code: "05701", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Catemu", code: "05702", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Llaillay", code: "05703", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Panquehue", code: "05704", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Putaendo", code: "05705", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Santa María", code: "05706", provincia: "San Felipe de Aconcagua", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Quilpué", code: "05801", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Limache", code: "05802", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Olmué", code: "05803", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
Comuna.find_or_create_by_name!(name: "Villa Alemana", code: "05804", provincia: "Marga Marga", region: "Valparaíso", region_number: "V")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")
#Comuna.find_or_create_by_name({name: "", code: "", provincia: "", region: "", region_number: "")